### ISSUE TITLE
Multiple callsigns for the same facility

### ISSUE THREAD

**Issue by collink2451** [vatsimnetwork/atc-bookings#8]
I integrated the API into the ZBW website and due to the nature of our booking system and our events system we have an entry for every callsign for every rostered position for the event.
[Since we are inputting all of the callsigns it does not look very good when we output to the booking site.](https://prnt.sc/26x7p7r)
I think it would be useful for other developers to display all of these callsigns in a different way, so I think we should continue to push all of the callsigns to the site.
I would like to suggest hiding duplicate facilities, this can be done by filtering out the middle character so BOS_1_CTR and BOS_2_CTR both become BOS_CTR and displaying only 1 for each base callsign. This could be done for all entries but I believe it would be most effective for the entries with the type "event".
Further development could be done to allow displaying all of the callsigns on hovering over the event tag but that isn't always necessary.

**Comment by mbozwood** [comment]
I have pushed the change for this. 
**N.B** - This only impacts our frontend timeline and has no impact on the API, all bookings in the API return as they were sent to us.
